version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: offer_browser_db
      MONGO_AUTH_SOURCE: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis
    ports:
      - "8082:8081"

  lotto:
    container_name: browser
    image: 135808915638.dkr.ecr.eu-north-1.amazonaws.com/browser1:latest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APP_NAME: OfferBrowserPrototype
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_USER: admin
      MONGO_PASSWORD: admin123
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: offer_browser_db
      MONGO_AUTH_SOURCE: admin
      SERVER_PORT: 8080
      JWT_SECRET: yourSuperSecretKeyThatIsAtLeast32CharactersLong
      JWT_ISSUER: offer-browser-prototype
      JWT_EXPIRATION: 3600000
      SPRINGDOC_API_DOCS_PATH: /v3/api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRINGDOC_PACKAGES: com.example.offerbrowserprototype.infrastructure.web,com.example.userbridge.infrastructure.api
      PROVIDER_ONE_API_URL: https://api.providerone.com/job-offers

      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_USERNAME: kapitanrex91@gmail.com
      MAIL_PASSWORD: ymfj bths zoab tfyf

      MAIL_SMTP_AUTH: "true"
      MAIL_SMTP_STARTTLS: "false"
      MAIL_SMTP_SSL_ENABLE: "true"
      SPRING_TIMEZONE: UTC
      PYTHON_PATH: /usr/bin/python3
      PYTHON_SCRIPT_PATH: scripts/scraper.py
      PYTHON_OFFER_URL_SCRAPER: src/main/resources/scripts/scrape_offer_from_url.py

      DAILY_OFFERS_EMAIL_RECIPIENT: kapitanrex91@gmail.com

    build:
      context: .
      dockerfile: Dockerfile

volumes:
  mongodb_data:
  redis_data: