services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  browser:
    image: 135808915638.dkr.ecr.eu-north-1.amazonaws.com/browser1:1.8
    container_name: browser
    ports:
      - "8080:8080"
    environment:

      - SPRING_DATA_MONGODB_URI=mongodb://admin:adminpassword@mongodb:27017/offerbrowserdb

      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
