version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin        # Ustawienie nazwy użytkownika
      MONGO_INITDB_ROOT_PASSWORD: admin123     # Ustawienie hasła użytkownika
    ports:
      - "27017:27017"                         # Mapowanie portów
    volumes:
      - mongodb_data:/data/db                 # Przechowywanie danych w wolumenie

volumes:
  mongodb_data:
