#spring.application.name=OfferBrowserPrototype
#
#spring.cache.type=redis
#spring.cache.redis.time-to-live=600000
#offer.cache.expiration=10
#
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#
#spring.data.mongodb.uri=mongodb://admin:admin123@localhost:27017/offer_browser_db?authSource=admin&readPreference=primary
#
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#
#server.port=8080
#
#
#logging.level.org.springframework.data.mongodb.core=DEBUG
#logging.level.org.springframework.data.redis=DEBUG
#
#
#jwt.secret=yourSuperSecretKeyThatIsAtLeast32CharactersLong
#jwt.issuer=offer-browser-prototype
#jwt.expiration-time-ms=3600000
#
#
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.packages-to-scan=com.example.offerbrowserprototype.infrastructure.web,com.example.userbridge.infrastructure.api
#
#
#provider.one.api.url=https://api.providerone.com/job-offers
#
#spring.scheduling.enabled=true
#job.offer.scheduler.cron=0 0 * * * *
#python.script.scheduler.cron=0 0 6,12,18,23 * * *
#daily.unapplied.offers.cron=0 0 17 * * *
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=userbridge9@gmail.com
#spring.mail.password=mnuv bxzq bvla oieg
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
#spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
#spring.mail.properties.mail.debug=false
#
#
#spring.jackson.time-zone=UTC
#
#python.path=C:/Users/przem/AppData/Local/Programs/Python/Python313/python.exe
#python.script.path=scripts/scraper.py
#python.script.offer-url-scraper=src/main/resources/scripts/scrape_offer_from_url.py
#
#
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.check-template-location=true
