# ===============================
# APP
# ===============================
spring.application.name=OfferBrowserPrototype
server.port=8080

# ===============================
# DATABASE - POSTGRES
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/pgDB
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# REDIS
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
redis.cache.ttl=600000

# ===============================
# JWT
# ===============================
jwt.secret=yourSuperSecretKeyThatIsAtLeast32CharactersLong
jwt.issuer=offer-browser-prototype
jwt.expiration-time-ms=3600000

# ===============================
# MAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=userbridge9@gmail.com
spring.mail.password=mnuv bxzq bvla oieg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.debug=false

# ===============================
# PYTHON
# ===============================
python.script.scheduler.url=http://localhost:8080/api/python-script/run
python.script.scheduler.cron=0 0 6,12,18,23 * * *

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.data.redis=INFO
logging.level.org.springframework.boot=INFO

# ===============================
# CORS / BASE URL
# ===============================
app.cors.allowed-origin=http://localhost:8080
app.server.base-url=http://localhost:8080
