spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/offer_browser_db

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
