spring.application.name=OfferBrowserPrototype

# W??czanie/wy??czanie cache Redis
spring.cache.type=redis

# Konfiguracja czasu wyga?ni?cia cache'a (przyk?adowo 10 minut)
offer.cache.expiration=10

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# MongoDB configuration
spring.data.mongodb.uri=mongodb://admin:admin123@localhost:27017/offer_browser_db?authSource=admin



# Exclude autoconfiguration classes
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Server configuration
server.port=8080

# Logging configuration
logging.level.org.springframework.data.mongodb.core=DEBUG

# JWT configuration
jwt.secret=yourSuperSecretKeyThatIsAtLeast32CharactersLong
jwt.issuer=offer-browser-prototype
jwt.expiration-time-ms=3600000


# SpringDoc configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.example.offerbrowserprototype.infrastructure.web,com.example.userbridge.infrastructure.api

# Swagger address and properties
http://localhost:8080/swagger-ui.html


provider.one.api.url=https://api.providerone.com/job-offers


# Harmonogramowanie zada?
spring.scheduling.enabled=true

# Cron expression for scheduled fetching of job offers (default: every hour at minute 0)
job.offer.fetch.cron=0 0 * * * *


# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=userbridge9@gmail.com
spring.mail.password=mnuv bxzq bvla oieg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



spring.jackson.time-zone=UTC


# ?cie?ka do interpretera Pythona
# W ?rodowisku deweloperskim (Windows)
python.path=C:/Users/przem/AppData/Local/Programs/Python/Python313/python.exe

# ?cie?ka do skryptu Python
# Skrypt znajduje si? w zasobach projektu (classpath: resources/scripts/scraper.py)
python.script.path=scripts/scraper.py


# Python Script Scheduler
python.script.scheduler.enabled=true
python.script.scheduler.cron=0 0 6,12,18,23 * * *  # Codziennie o 6:00, 12:00, 18:00, 23:00

# Scheduled Job Offer Fetcher
job.offer.scheduler.enabled=false
job.offer.scheduler.cron=0 0 * * * *  # Co godzin?# 