
spring.data.mongodb.uri=mongodb://admin:adminpassword@mongodb:27017



spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}


jwt.secret=${JWT_SECRET:yourSuperSecretKeyThatIsAtLeast32CharactersLong}
jwt.issuer=${JWT_ISSUER:offer-browser-prototype}
jwt.expiration-time-ms=${JWT_EXPIRATION_TIME_MS:3600000}


spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:userbridge9@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:mnuv bxzq bvla oieg}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.ssl.trust=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST:smtp.gmail.com}
spring.mail.properties.mail.smtp.ssl.protocols=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_PROTOCOLS:TLSv1.2}
spring.mail.properties.mail.debug=${SPRING_MAIL_PROPERTIES_MAIL_DEBUG:false}


spring.application.name=${SPRING_APPLICATION_NAME:OfferBrowserPrototype}
server.port=${SERVER_PORT:8080}


cache.expiration=${CACHE_EXPIRATION:10}
redis.cache.ttl=${REDIS_CACHE_TTL:600000}


app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://ec2-16-171-116-191.eu-north-1.compute.amazonaws.com:8080}


python.script.scheduler.url=${PYTHON_SCRIPT_SCHEDULER_URL:http://ec2-16-171-116-191.eu-north-1.compute.amazonaws.com:8080/api/python-script/run}
python.script.scheduler.cron=0 0 6,12,18,23 * * *

logging.level.org.springframework.data.mongodb.core=${LOGGING_MONGO_LEVEL:DEBUG}
logging.level.org.springframework.data.redis=${LOGGING_REDIS_LEVEL:DEBUG}
logging.level.org.springframework.boot=${LOGGING_BOOT_LEVEL:DEBUG}


app.server.base-url=${APP_SERVER_BASE_URL:http://ec2-16-171-116-191.eu-north-1.compute.amazonaws.com:8080}


spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017