spring.application.name=${SPRING_APP_NAME:OfferBrowserPrototype}
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
offer.cache.expiration=10

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.mongodb.uri=mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin123}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB_NAME:offer_browser_db}?authSource=${MONGO_AUTH_SOURCE:admin}&readPreference=primary
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=${SERVER_PORT:8085}

logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.springframework.data.redis=DEBUG

jwt.secret=${JWT_SECRET:yourSuperSecretKeyThatIsAtLeast32CharactersLong}
jwt.issuer=${JWT_ISSUER:offer-browser-prototype}
jwt.expiration-time-ms=${JWT_EXPIRATION:3600000}

springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH:/v3/api-docs}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
springdoc.packages-to-scan=${SPRINGDOC_PACKAGES:com.example.offerbrowserprototype.infrastructure.web,com.example.userbridge.infrastructure.api}

provider.one.api.url=${PROVIDER_ONE_API_URL:https://api.providerone.com/job-offers}
spring.scheduling.enabled=true

job.offer.scheduler.cron=0 0 * * * *
python.script.scheduler.cron=0 0 6,12,18,23 * * *
daily.unapplied.offers.cron=0 0 17 * * *

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:userbridge9@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:mnuv bxzq bvla oieg}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS:true}
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.debug=false


spring.jackson.time-zone=${SPRING_TIMEZONE:UTC}

#python.path=${PYTHON_PATH:/usr/bin/python3}
#python.script.path=${PYTHON_SCRIPT_PATH:scripts/scraper.py}
#python.script.offer-url-scraper=${PYTHON_OFFER_URL_SCRAPER:src/main/resources/scripts/scrape_offer_from_url.py}

python.path=C:/Users/przem/AppData/Local/Programs/Python/Python313/python.exe
python.script.path=scripts/scraper.py
python.script.offer-url-scraper=src/main/resources/scripts/scrape_offer_from_url.py

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true
