package com.offerbrowserprototype.domain.offer;

import com.offerbrowserprototype.domain.offer.dto.OfferDTO;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class OfferMapperTest {

    @Test
    void mapToEntity() {
        OfferDTO offerDTO = new OfferDTO();
        offerDTO.setId(1L);
        offerDTO.setTitle("Test Title");
        offerDTO.setDescription("Test Description");
        offerDTO.setLocation("Test Location");
        offerDTO.setSalaryRange("Test Salary Range");
        offerDTO.setTechnologies("Test Technologies");

        Offer offer = OfferMapper.mapToEntity(offerDTO);

        assertNotNull(offer);
        assertNull(offer.getId()); // ID should be null because it's usually generated by the database
        assertEquals("Test Title", offer.getTitle());
        assertEquals("Test Description", offer.getDescription());
        assertEquals("Test Location", offer.getLocation());
        assertEquals("Test Salary Range", offer.getSalaryRange());
        assertEquals("Test Technologies", offer.getTechnologies());
    }

    @Test
    void mapToDto() {
        Offer offer = new Offer();
        offer.setId(1L);
        offer.setTitle("Test Title");
        offer.setDescription("Test Description");
        offer.setLocation("Test Location");
        offer.setSalaryRange("Test Salary Range");
        offer.setTechnologies("Test Technologies");

        OfferDTO offerDTO = OfferMapper.mapToDto(offer);

        assertNotNull(offerDTO);
        assertEquals(1L, offerDTO.getId());
        assertEquals("Test Title", offerDTO.getTitle());
        assertEquals("Test Description", offerDTO.getDescription());
        assertEquals("Test Location", offerDTO.getLocation());
        assertEquals("Test Salary Range", offerDTO.getSalaryRange());
        assertEquals("Test Technologies", offerDTO.getTechnologies());
    }
}